### ISSUE TITLE
Typo "witch" instead of "with"

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#133]
![Screenshot from 2022-07-22 07-54-07](https://user-images.githubusercontent.com/414797/180372596-1f02ab5d-506e-4ac8-8b3b-19227147ab17.png)

**Comment by emilylouisesimonis** [comment]
@henri-egger could you please correct the whole sentence? 
It should have been: 

Grow your business with data.​ Discover the benefits you can get by joining the ​Open Data Hub services.

**Comment by henri-egger** [comment]
Okay, changed it on testingmachine but i need some help with git and github with taking it to production, something doesn't seem right to me. I'll have to wait for @RudiThoeni or @dulvui.

**Comment by henri-egger** [comment]
Okay changes are now on Production.
