### ISSUE TITLE
released "under" an Open Data License

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#134]
I think it should be "under" instead of "with"

![Screenshot from 2022-07-22 07-57-58](https://user-images.githubusercontent.com/414797/180373152-e0267598-e9af-4caf-92d9-bf08e48b1304.png)

**Comment by emilylouisesimonis** [comment]
@henri-egger could you please corrct this?

**Comment by henri-egger** [comment]
Okay, changed it on testingmachine but i need some help with git and github with taking it to production, something doesn't seem right to me. I'll have to wait for @RudiThoeni or @dulvui.

**Comment by henri-egger** [comment]
Okay changes are now on Production.
