### ISSUE TITLE
Contact us form on OpenDataHub.com seams not to work

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#135]
I have tried the form on https://opendatahub.com/start/ (Btw. the link/URL called "/start/" is kind of strange)

The only feedback I got was that in the form UI a text stating "Your request has been processed." gets shown. I didn't get any e-mail and I fear, the form didn't send any mail, neither to me as a requester, nor to a destination e-mail.

![Screenshot from 2022-07-22 08-12-11](https://user-images.githubusercontent.com/414797/180374840-96327191-e368-4df6-9e18-b8a4cf783c02.png)

**Comment by henri-egger** [comment]
I also noticed the URL, i will change it. Regarding the functionality of the contact form, do you happen to know wether this came with my design changes or might it have already broken earlier?
Just asking because i did not change the code that is responsible for this section of the page.

**Comment by emilylouisesimonis** [comment]
I've actually never tested it before either, the emails should come to help@opendatahub.bz.it, right? 
@henri-egger, maybe try asking @LucaMiotto iff he can tell you anything more. 
I also think it should also be updated to help@opendatahub.com

We wanted to work on this form later, but let's try now to gather info to understand how it works ...or if it doesn't! :)

**Comment by henri-egger** [comment]
Hmmmm... Wonder why the contact form is not working...

![image](https://user-images.githubusercontent.com/105497721/180403367-79c9f0e4-d200-4805-af6d-8c20df332b25.png)

**Comment by dulvui** [comment]
The contact form works now again under https://opendatahub.com/contact/
If it still doesn't work try to clean the browser cache of the site.

@ohnewein The emails of this form are visible in the issue tracker. Your Test 1 and Test 2 are also visible there
