### ISSUE TITLE
Promote Element / Matrix channel on OpenDataHub.com

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#136]
Would it be possible to add also a link to the Element / Matrix channel in the footer of the OpenDataHub.com website? At the moment there are the links to the fb page, to the github organization and to the telegram channel.

- [x] add https://matrix.to/#/#main-room-odh22:matrix.virtual.software.bz.it (which could be the first entry, because we are planning to have the main discussions on this channel)

![Screenshot from 2022-07-22 12-10-43](https://user-images.githubusercontent.com/414797/180417751-d81da685-7ddf-4928-b464-8ea81f741530.png)

**Comment by emilylouisesimonis** [comment]
@henri-egger when you come back, could you please add the link to Element (Matrix) in the footer?
At this link I found the vectors if we need them: https://github.com/vector-im/logos/tree/master/element

**Comment by henri-egger** [comment]
I will insert it as soon as i am back.

**Comment by emilylouisesimonis** [comment]
The Element / Matrix channel link has been added in the footer of the OpenDataHub.com website
