### ISSUE TITLE
Datasets page: visualisation error

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#144]
I report that I still see an error in the display of the Datasets page: there are some "holes" where the datasets are not displayed.

![2022-08-31_10-38-52](https://user-images.githubusercontent.com/38345889/187635605-08bc1253-20cc-4063-b585-ca237aa8535d.png)

**Comment by ila131** [comment]
You can see the changes on testingmachine.

**Comment by emilylouisesimonis** [comment]
@ila131 I can still see the error. I cleared my cache. Maybe I will try again later on.
Thanks!

**Comment by ila131** [comment]
Let me know.

**Comment by emilylouisesimonis** [comment]
@ila131 has fixed it.
