### ISSUE TITLE
Footer visualisation error [mobile version]

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#146]
I report that I see an error in the display of the logo in the footer of the opendatahub.com website.
In the mobile version of the website, the logo is stretched:

![Open Data Hub Südtirol - Alto Adige](https://user-images.githubusercontent.com/38345889/187640692-d5910646-20d8-4aaf-b3c5-8f4d92caaddf.png)

**Comment by ila131** [comment]
This problem persists only on iPhone. We tried on an Android mobile device and the image is displayed correctly.
