### ISSUE TITLE
As a user I would like to see an improvement of the website homepage

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#147]
As a user I would like to see a **title**, before the text "Open Data Hub is the cross-border digital platform that helps start-ups, companies and research institutes to develop digital solutions based on real data. It connects data from different data providers and makes this data easily available for data consumer." in the opendatahub.com website homepage.

The title should be:
"**Develop digital solutions based on real data.**"

Graphically I would imagine something this:

![2022-08-31_11-13-38](https://user-images.githubusercontent.com/38345889/187643493-9b2b8454-8fd3-43f6-838c-a4a17adb369e.png)

**Comment by ila131** [comment]
You can see the changes on Testingmachine.

**Comment by emilylouisesimonis** [comment]
Perfect!! Thanks! 

Is it also possible to delete the call to action "Discover our services" button?

**Comment by ila131** [comment]
Sure thing. You can see it now on testingmachine ;)

**Comment by emilylouisesimonis** [comment]
@ila131 has fixed it.
