### ISSUE TITLE
As a user I would like to see an improvement to the website name

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#148]
As a user, I would like to see an improvement to the opendatahub.com website name, both in the top display of the page name and in Google search.

I would expect to no longer find "Südtirol - Alto Adige".

**Based on the length available for the Google search display**, I would imagine:

- Open Data Hub - Develop digital solutions based on real data _(but maybe this is too long)_
- Open Data Hub - Get real data
or
- Open Data Hub - Access, Share, Visualise

Page name:
![2022-08-31_11-05-21](https://user-images.githubusercontent.com/38345889/187644350-1f741f5e-135e-4028-872b-f581f1eb3195.png)

Google search:
![2022-08-31_11-04-44](https://user-images.githubusercontent.com/38345889/187644402-59a7425c-29fb-461c-9771-9c25667f07b8.png)

**Comment by dulvui** [comment]
This can be simply fixed by changing the title tag in the html header. But it may take some days or even weeks until Google updates it on the search.

When you decide which title to use I will change it.

**Comment by emilylouisesimonis** [comment]
@ohnewein Which title would you suggest?

**Comment by dulvui** [comment]
The title "Open Data Hub - Develop digital solutions based on real data" is online now.
Lets see in some days/weeks when Google updates the search result, if it fits.
