### ISSUE TITLE
As an Open Data Hub Manager I want to have online the new dataset about the flight schedule in order to promote the dataset in the Newsletter and at the SFScon

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#154]
To add the dataset the task are:
- [x] find a name for the data set;
- [ ] publish the dataset on the Open Data Hub website
- [x] add the dataset to the Open Data Hub presentation

**Comment by ila131** [comment]
@rcavaliere Do you have a slide or a docs sheet with some information about this dataset?

**Comment by sseppi** [comment]
@rcavaliere we would like to prepare the dataset on the testing Open Data Hub website, in order to be ready as soon as we go online with the new dataset.

Since we are promoting the new Flight Data Web component in the newsletter, and SkyAlps as data provider. I can expect that someone will look and/or ask for it.

**Comment by ila131** [comment]
@rcavaliere do you have any news about the Flight Data? Has the data integration been completed?

**Comment by rcavaliere** [comment]
@ila131 it is in the hand of @dulvui that needs to integrate the Data Collector in our testing environment. After check we can test everything, and if OK put the dataset online in production

**Comment by ila131** [comment]
Perfect, thank you for letting me know! @rcavaliere

**Comment by sseppi** [comment]
The scheduled data are now online

End-point: https://mobility.api.opendatahub.com/v2/flat (Dataset "Flight")

@ila131 can you please update the website and the presentation?

**Comment by rcavaliere** [comment]
@ila131 what kind of information do you need to integrate this information on the web-site?

**Comment by ila131** [comment]
Hey @rcavaliere,
would be nice to have a short description of the dataset, an image and a use case :)

Thank you

**Comment by emilylouisesimonis** [comment]
[REMINDER] @rcavaliere - Could you answer - even schematically - at this point?

> Hey @rcavaliere, would be nice to have a short description of the dataset, an image and a use case :)

Thank you!

**Comment by rcavaliere** [comment]
@emilylouisesimonis yes of course, it's on my to-do-list. My plan is to do this in the next Open Data Hub Customer Care sprint

**Comment by emilylouisesimonis** [comment]
If you agree, I would proceed to write the following:

title
> **Flight Data**

[Datasets](https://opendatahub.com/datasets) > [Mobility](https://opendatahub.com/datatype/mobility)

text

> This dataset contains information on real-time data and scheduled flights. Through this API you will have an overview of the SkyAlps timetable, with up-to-date information like prices, times, destinations, and more. 

chart

<html>
<body>


  |  
-- | --
Output | JSON, mime-type application/json
API version | v2
Swagger URL | https://mobility.api.opendatahub.bz.it/
StationType | Flight
Wiki | Flight Data API Wiki
Sources | SkyAlps
OpenData | Open Data


</body>
</html>

Output	JSON, mime-type application/json
API version	v2
Swagger URL	https://mobility.api.opendatahub.bz.it/
StationType	[Flight](https://mobility.api.opendatahub.com/v2/flat/Flight)
Wiki | [Flight Data API Wiki](https://github.com/noi-techpark/odh-docs/wiki/Flightdata-API)
Sources	SkyAlps
OpenData	Open Data

image: 
![ross-parmly-rf6ywHVkrlY-unsplash](https://user-images.githubusercontent.com/38345889/218082625-861dcf6f-7d42-48be-859c-f4f113100222.jpg)

---
@rcavaliere 
Does that sound right? The StationType link also?
Is there any other information we should add?

@ila131 If everything is OK can you add this dataset?

**Comment by rcavaliere** [comment]
@emilylouisesimonis 

The end-point to this dataset is: https://mobility.api.opendatahub.com/v2/flat/Flight

In order to see the current flights in action, use these API calls:
https://mobility.api.opendatahub.com/v2/flat/Flight?where=sactive.eq.true
https://mobility.api.opendatahub.com/v2/flat/Flight/*/latest?where=sactive.eq.true

I would also mention that it is possible to get also price indications of the flights.

I would also give visibility to a nice wiki page prepared by @mrabans: https://github.com/noi-techpark/odh-docs/wiki/Flightdata-API

**Comment by emilylouisesimonis** [comment]
@rcavaliere 
So the title "StationType" should be changed to "**Endpoint**", correct? 

How do we add the call links in the table I put above? We call them "**API calls**" and add both links ...or we need two different descriptions? (if so, which?)

The rest seems to me to be there already:

> This dataset contains information on real-time data and scheduled flights. Through this API you will have an overview of the SkyAlps timetable, with up-to-date information like **prices**, times, destinations, and more.

> Wiki | [Flight Data API Wiki](https://github.com/noi-techpark/odh-docs/wiki/Flightdata-API)

But if it is not understandable, let me know that we change.

Thanks, Emily

**Comment by rcavaliere** [comment]
@emilylouisesimonis you can also leave StationType.
Yeah, I see the challenge here. Let's consider here the generic link https://mobility.api.opendatahub.com/v2/flat/Flight
For the rest, fine for me. Sorry I had a look very quickly, so I missed that these details were already here.

**Comment by ila131** [comment]
Thank you for your help @emilylouisesimonis @rcavaliere 
You can now see the flight dataset on testingmachine. Let me know if everything is ok!

Best,

Ilaria

**Comment by emilylouisesimonis** [comment]
Super! Thanks @rcavaliere & @ila131 
It seems to be working, we can go into production on Monday.

**Comment by mrabans** [comment]
@emilylouisesimonis @rcavaliere fyi, I've forwarded the https://opendatahub.com/datasets/mobility/flight/ to be used by Zeppelin
