### ISSUE TITLE
As and Open Data Hub manager I want the Weather Dataset Updated with the latest information.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#155]
As you can see from the screenshot below, while I was browsing the Open Data Hub Website, I noticed that the Weather Dataset (https://opendatahub.com/datasets/traffic/weather/) has some missing/wrong information.
![Image](https://user-images.githubusercontent.com/7909989/196191731-e9603eef-b2d5-44a6-8dba-6345b422da32.png)
I noticed that:
- [x] In the sources Eurac Research is missing;
- [x] Data of Famas System are mentioned as restricted, but Famas System is missing as Data Provider. Can you please verify with Roberto if Famas System is providing private data and update the information (add Famas System ad data provider or change the sentece about the restricted data) of the dataset site?

**Comment by emilylouisesimonis** [comment]
@ila131 And then, could you also update the same information in the presentation?

**Comment by rcavaliere** [comment]
Famas System is not a Data Provider of the Open Data Hub! Which dataset are you referring, @sseppi ?

**Comment by sseppi** [comment]
@rcavaliere I refer to the Weather dataset.

You can see it at the following link:
https://opendatahub.com/datasets/traffic/weather/

**Comment by rcavaliere** [comment]
@sseppi it's all correct. We have just these two Data Providers here

**Comment by sseppi** [comment]
@rcavaliere ww have also Eurac that provides weather data now. Don't they?

Moreover down right (just below the two buttons) there is the following text "_FAMAS System data is closed and restricted to a project collaboration ([contact us](mailto:help@opendatahub.com?subject=Collaboration request for dataset Weather) if you are interested in this data.)_"

Do we have closed data for this dataset? If not, I would ask @ila131 to delete the sentence, otherwise we have to update it.

**Comment by rcavaliere** [comment]
@sseppi I answered too quickly. EURAC is also a Data Provider, of course!
Please delete the reference to Famas System.

**Comment by sseppi** [comment]
@rcavaliere thanks!

**Comment by rcavaliere** [comment]
yes!

**Comment by ila131** [comment]
You can see the changes on testingmachine. Please, let me know!

**Comment by sseppi** [comment]
Thank you @ila131 !

Since is completely open, I would suggest to move the Weather Dataset Between the "Tourism Region" and the "Weather Forecast" dataset. So we keep the standard sorting that shows the completely open data dataset before.

**Comment by ila131** [comment]
Sure thing, you can see the changes on testingmachine. @sseppi

**Comment by emilylouisesimonis** [comment]
I've checked: https://opendatahub.testingmachine.eu/datasets/traffic/weather/
Looks good to me, I think we can go into production with this one.
