### ISSUE TITLE
As an Open Data Hub user I would like to see in the dataset page the reference to the bike charger dataset

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/opendatahub-website#156]
Presentation already contains the information and the details to be published, but the web site does not contain this information.

**Comment by ila131** [comment]
Sorry my mistake, now I implemented it.
Is there a URL to link with the the BikeCharger StationType?

**Comment by rcavaliere** [comment]
@ila131 do you mean this: https://mobility.api.opendatahub.com/v2/flat,node/BIKE_CHARGER/*/latest ?

**Comment by ila131** [comment]
Yes, many thanks @rcavaliere

**Comment by ila131** [comment]
You can see the changes on testingmachine. Please, let me know!

**Comment by emilylouisesimonis** [comment]
I've checked: https://opendatahub.testingmachine.eu/datasets/mobility/bikecounter/ 
Looks good to me, I think we can go into production with this one.
