### ISSUE TITLE
As an Open Data Hub user I would like to see "Web Component" in the opendatahub.com menu

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#157]
I would insert the menu item 'Web Components' between 'Use Cases' and 'Quickstart'.

This 'Web Components' menu item will lead to: https://webcomponents.opendatahub.com/

![2022-10-20_08-36-51](https://user-images.githubusercontent.com/38345889/196874470-da84ab7d-c418-466c-b306-174fdb45eaa9.png)

**Comment by sseppi** [comment]
It could be a good idea and it will provide more visibility to the Web Components.

**Comment by ila131** [comment]
You can see the changes on testingmachine :) 
If everything is ok, I will put everything in prod.

**Comment by sseppi** [comment]
For me it works fine, the only thing that I'm asking myself is, if it wouldn't be better to switch 'use cases' and 'Web Compoents'.

@emilylouisesimonis what do you think?

**Comment by emilylouisesimonis** [comment]
why?

**Comment by sseppi** [comment]
To keep the ways you can browse the data near.

**Comment by sseppi** [comment]
The point has been added and the order of the single menu entries will be discussed during the review of the entire menu.
