### ISSUE TITLE
As an Open Data Hub user I would like to see a video preview in the Open Data Hub Day event page of the opendatahub.com

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#161]
E.g. In the Open Data Hub Day 2022 - Programm - https://opendatahub.com/odhday22/ 

@ila131 we can talk about how to do it best

**Comment by emilylouisesimonis** [comment]
@ila131 I have checked https://opendatahub.testingmachine.eu/video-library/ the structure is fine and has been approved!
But in the links to the slides there are some small errors (e.g. in the first video there are slides from the second and vice versa). 
Could you check and update it, so that we can go online? 

As a subtitle to "Video Library" I would write:
> Check out all the videos and presentations given at past Open Data Hub Days and learn more about Open Data Hub-related projects.

Thank you very much!
Emily

**Comment by emilylouisesimonis** [comment]
- [ ] Note for the future: it would be interesting to add a filtering and tagging system (as on the Dataset page) to be able to find videos related to a certain topic more quickly.

**Comment by ila131** [comment]
Hey @emilylouisesimonis,
I did the modifications that you suggested:
- Fixed links to slides
- Changed video-library subtitle
You can see the changes on testingmachine

Thank you :)

Ilaria
