### ISSUE TITLE
As an Open Data Hub user I would like to see an "About us" page in the opendatahub.com website

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#165]
@ila131 we need to add an "About us" page in the opendatahub.com website.

The idea is to change the "Contact us " button and transform it 'About us' with a submenu containing the two buttons 'About us' and 'Contact us'.

![Image](https://user-images.githubusercontent.com/38345889/214532386-d6b53b00-d6c7-45b5-890e-510f3a92faf1.png)

The format we would have in mind is the same as the single page use case (https://opendatahub.com/use-cases-kultivas/).
But we would like to do a test without images.

The texts are as follows:

---

ABOUT US
**The evolution of the Open Data Hub Project**

Since 2010, Open Data Hub has stood for innovative solutions in the field of Open Data and is now an important partner of companies, research institutes and developers at a European level with the main goal of enabling the development of innovative digital solutions based on real data. 

-------

The Open Data Hub project began in South Tyrol in 2010 with the aim of grouping data collected from a series of European projects in the field of mobility research and development. This data comes from different sources, often with complex APIs. The Open Data Hub translates these APIs into well- documented Open Specification APIs, in order to simplify and improve the work of developers interested in creating apps, websites and other systems.

In 2016, tourism data was added to the field of mobility, again by providing easy-to-read, machine-readable, high quality APIs.

Today, the main objective of the Open Data Hub is to enable the development of digital solutions based on real data by expanding the collection and exchange of data on a European level working in the Data Spaces: Mobility, Tourism and Agriculture.

------
_[as a quote]_

“The main issue we try to address is that people who develop advanced apps, with advanced algorithms, also need data (if possible, simple and of high quality.) Otherwise the algorithms and the related innovative business models do not work. Thanks to the Open Data Hub, we try to provide a large amount of high quality data, reducing the so-called "cold start problem.”
PATRICK OHNEWEIN
Head of Unit of Digital Technologies at NOI Techpark

------

@ila131  please let us know if you have any doubts!

Thanks, 
Emily & Tania

**Comment by ila131** [comment]
@emilylouisesimonis Thank you, I will let you know if I have any doubts!

**Comment by emilylouisesimonis** [comment]
@ila131 Regarding the 'Contact us' page, we would like to change the text. 

The text we would like is this:

-----

**Get in touch with us**
Welcome to the Open Data Hub contact us page. Here you can get in touch with the Open Data Hub team if you have any questions, need help, or would like to collaborate with us. 

We’re always happy to hear from our community and to provide support and advice on how to access and share data. We encourage you to reach out to us by submitting a form on this page. We will do our best to respond to your inquiry as soon as possible. You can also contact us for general inquiries or to suggest ideas for new data sets or collaborations. We look forward to hearing from you!

-----

But the text is a bit longer than what is currently possible.

Do you think a way could be found to add this part (_We’re always happy to hear from our community and to provide support and advice on how to access and share data. We encourage you to reach out to us by submitting a form on this page. We will do our best to respond to your inquiry as soon as possible. You can also contact us for general inquiries or to suggest ideas for new data sets or collaborations. We look forward to hearing from you!_) perhaps not as a "subtitle" but as "text"?

**Comment by ila131** [comment]
@emilylouisesimonis @taniamarcadella Hey,
You can see the changes on testingmachine. I also changed the text of the "contact-us" as you suggested.

Let me know if everything is ok,
Thank you

Ilaria

**Comment by emilylouisesimonis** [comment]
@taniamarcadella For the about us page, maybe we should find some pictures - now it does not look very appealing to me. 
Maybe we can also reason about the infographics.

**Comment by taniamarcadella** [comment]
@emilylouisesimonis I agree with you.

**Comment by sseppi** [comment]
@emilylouisesimonis I think we can close this issue, is it fine for you?
