### ISSUE TITLE
As an Open Data Hub manager I want the link to the beta of the Data Browser 2.0 on the Open Data Hub website, to  easily promote the beta version of the Data Browser in our community.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#167]
link to beta: https://v2-beta.databrowser.opendatahub.com/

**Comment by sseppi** [comment]
link to beta: https://v2-beta.databrowser.opendatahub.com/

**Comment by emilylouisesimonis** [comment]
@ila131 we would need to add a new box on the Quickstart page (https://opendatahub.com/quickstart/) of the Open Data Hub website to also present the BETA version of the Data Browser.

I would write what follows:

title
> **Data Browser BETA**

text
>  Browse and discover data in the BETA version of the Data Browser 

learn more
> [link] https://v2-beta.databrowser.opendatahub.com/

If @sseppi agrees I would add it as a **fourth box** (in place of what is now the "Mobility API" box, after "Web Components")

Thank you very much,
Emily

**Comment by ila131** [comment]
Hey @emilylouisesimonis,
should I put the link also in the footer?

**Comment by ila131** [comment]
In the meantime you can see the changes on testingmachine @emilylouisesimonis

**Comment by emilylouisesimonis** [comment]
> Hey @emilylouisesimonis, should I put the link also in the footer?
I wouldn't put it on for now.

Perfect. Seems to be working. Thanks!

**Comment by sseppi** [comment]
Hi @emilylouisesimonis and @ila131 

thank you for the great work!
If you agree, I will put all changes online in production on Monday.

Best
