### ISSUE TITLE
As an Open Data Hub Project content manager I would change the Data Sharing image on the opendatahub.com website

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#168]
[#53](https://github.com/noi-techpark/opendatahub-customer-care/issues/53)

@ila131 I could not tag you in the reference issue. I will post the thread here:

Below the new photo we chose for the opendatahub.com website representing Data Sharing. 

The webages where we have to replace the old "Data Sharing" photo with the new one are:

- home: Data Sharing
- subpage Data Sharing
- Services: Data Sharing

![OpenDataHub-Data-Sharing-Luisa-by-Tania-Marcadella-3779](https://user-images.githubusercontent.com/38345889/215520028-47d5f9e8-e36f-4630-bfb4-b8842b5c5129.jpg)

**Comment by ila131** [comment]
Hey @emilylouisesimonis @taniamarcadella,
You can see the changes on testingmachine.

Thank you,

Ilaria
