### ISSUE TITLE
As an Open Data Hub website visitor I would like to see aligned images on the home page

### ISSUE THREAD

**Issue by ila131** [noi-techpark/opendatahub-website#169]
@emilylouisesimonis @taniamarcadella 
The new photo representing data sharing, in the home page, is not aligned with the other photos. Could you please give me a photo with the same dimensions as the others? 

<img width="1312" alt="data-sharing" src="https://user-images.githubusercontent.com/76970381/216098633-e495e535-016f-48d5-90a3-53308e38e402.png">

Thank you very much,

Ilaria

**Comment by taniamarcadella** [comment]
@ila131 I have just emailed you the photo in the correct format.

**Comment by ila131** [comment]
@taniamarcadella thank you very much!
You can see the new uploaded image on testingmachine.

**Comment by sseppi** [comment]
Hi!
Great news here!
I merged everything into prod... In a few minutes you should see everything online in production.

@emilylouisesimonis let me know if everything is ok... In the meantime I close this issue

**Comment by emilylouisesimonis** [comment]
Super! Thanks :)
