### ISSUE TITLE
As an Open Data Hub visitor I would need a better experience with the menu

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#173]
ToDo

- [ ] Menu (for both opendatahub.com and webcomponents.opendatahub.com)

**Comment by emilylouisesimonis** [comment]
As a first step - before redesigning the menu as a whole for both the Open Data Hub and the Web Component Store - it would at least be useful if the 'Web Components' button on the current menu opened the page in another tab of the browser [target=”_blank”], leaving the Open Data Hub site always open.

This is a transitional and not a definitive measure; but it might improve the situation for the time being.

@ila131, what do you think? Can we try?

**Comment by ila131** [comment]
@emilylouisesimonis sure!
You can see it on testingmachine.

Best,
Ilaria

**Comment by emilylouisesimonis** [comment]
This issue is releated to https://github.com/orgs/noi-techpark/projects/33/views/1?filterQuery=emily&pane=issue&itemId=21487932

**Comment by mrabans** [comment]
closing here
