### ISSUE TITLE
As a Open Data Hub manager I want that all Swagger and API links in the dataset are using opendatahub.com link, to avoid that our customer use deprecated .bz.it links.

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#179]
Navigating the dataset I noticed that all links to Swagger are pointing to the old domain .bz.it (see picture below)

![Schermata da 2023-03-10 09-46-05](https://user-images.githubusercontent.com/7909989/224270006-faec78ac-08da-4ea6-ac45-50c8cd79f431.png)

@ila131 can you please check all links (API, Swagger, etc.) of the datasets and change all links to the .com domain?

@emilylouisesimonis p.c.

**Comment by ohnewein** [comment]
Hi all,

you can find all links to opendatahub.bz.it on the opendatahub.com website using the following 2 commands:

`
$ wget --spider -r -nd -nv -H -l 3 -Dopendatahub.com,opendatahub.bz.it -w 2 -o run2.log https://opendatahub.com/
$ grep -i 'opendatahub.bz.it' run2.log 
`

Happy hacking!
Patrick

**Comment by ila131** [comment]
@ohnewein Thank you very much for your advice!

**Comment by ila131** [comment]
Hey all,
I changed the .bz.it domain to .com, you can see the changes on testingmachine.

Let me know if I forgot something :)

Ilaria
