### ISSUE TITLE
Remove unused files

### ISSUE THREAD

**Issue by henri-egger** [noi-techpark/opendatahub-website#198]
@emilylouisesimonis Just a quick question as I'm currently doing some code cleanup parallel to the design updates, are the screenshots in /src/themes/odh-fbe/images still relevant or can I delete them?

**Comment by henri-egger** [comment]
Same goes for /src/layouts/data-access/list-unused.html, /src/layouts/data-sharing/list-unused.html and /src/layouts/partials/contact-form-start.html, should I remove them?

**Comment by henri-egger** [comment]
Same goes for the entire /help route. Is it still in use? I haven't found a single link pointing to it. It's resources include:
src/content/help/_index.md
src/layouts/partials/contact-form-help.html
src/themes/odh-fbe/layouts/help/list.html

**Comment by emilylouisesimonis** [comment]
If there are no links, clean them up! They will be remnants from previous versions. 
Thanks,
Emily
