### ISSUE TITLE
Content, layout and route structuring

### ISSUE THREAD

**Issue by henri-egger** [noi-techpark/opendatahub-website#199]
@emilylouisesimonis @sseppi 

Looking at the structure of the odh-website implementation in Hugo while doing some cleanup, I have noticed that the way in which some of the content is structured could be done in a diffrent way to make the routing and content structuring clearer and simpler. The main benefit would be to have clearer source code but also the routing of the application will be more structured which provides the user with more information about his current position on the page.

To be more specific, I am talking about things like use-cases, events but also the pages for services such as data-access and data-sharing. I will try to explain myself through an existing example in the source code.

Current:
![image](https://github.com/noi-techpark/opendatahub-website/assets/105497721/e77c87a2-ba6b-4a7a-81a5-826b91ffd739)

Optimized:
![image](https://github.com/noi-techpark/opendatahub-website/assets/105497721/540a9c4b-ba14-45b2-8c7f-d1a720542fdf)

The same structure could be applied to the data and layouts directories.

Tell me what you think and whether this should be implemented or not.

**Comment by sseppi** [comment]
Hi @henri-egger ,

So if I understood correctly, to add a new use case using the optimized solution we will have to add a new folder named with the use case name, under the ``use-case`` folder. Do I understood right?

If so, I agree! In my point of view your  cleanup proposal is helpful in improving the structure of the website.

If @emilylouisesimonis agrees too, you can proceed with the optimization.

Best
Stefano

**Comment by henri-egger** [comment]
Yes @sseppi,

for the specific case of the use-cases yes. In general it would work like this that if a page is conceptually a sub-page of another page, it will exist as a subdirectory of the more general page.

Another example would be the bootcamp23 page. As it is a sub-page of the events page, the current bootcamp23 folder at the root of the content directory would be moved to be a subdirectory of the events folder.

The same goes for the yml data. just that instead of having folders, you have yml objects, so instead of having one file called events.yml and another called bootcamp23.yml, there would be a bootcamp23 object in the events.yml file holding the corrisponding data.

The layouts directory will be structured the same way as the content directory.

**Comment by emilylouisesimonis** [comment]
Hi Henri, that sounds like a very good idea. The use case structure was made like that by Ilaria, but I don't remember why (maybe we can ask her) 
The important thing is that the url remains as it is. Or if it is changed for example in https://opendatahub.com/use-cases/mentor/ there can be a redirect of the pages. 
Thanks, Emily

**Comment by henri-egger** [comment]
The changes are now integrated into the design-updates branch.

@maxglio Read the above issue to understand how the /events /services and /use-cases content, data and layouts are now structured.

I have also moved some data which was previously in the /data directory to the yaml section of the individual md pages. Otherwise the yaml data files would have gotten very big. Also it simplifies the filtering for the use-cases.
