### ISSUE TITLE
Should we add a browser icon for the open data hub website?

### ISSUE THREAD

**Issue by d3liaa** [noi-techpark/opendatahub-website#215]
I just noticed there isn't one. We could easily use the open data hub logo in black or white :)

**Comment by sseppi** [comment]
I agree with you @delia.

Il 16 ott 2023 17:00, Delia Mennitti ***@***.***> ha scritto:

I just noticed there isn't one. We could easily use the open data hub logo in black or white :)

**Comment by ohnewein** [comment]
Hi all I noticed the same issue.

https://opendatahub.com/favicon.ico

Is some empty gray block.

Google is doing it better than us: https://www.google.com/favicon.ico

@dulvui can you fix this?

**Comment by dulvui** [comment]
The fav icon was already fixed on https://opendatahub.testingmachine.eu/favicon.ico by @sseppi 
It just needs to be deployed to production, but there are some changes on testingmachine I don't know if they are ready for production.
If it is urgent, I can cherry-pick the commit with the fix to production. Should I wait for all changes in testing to go in production or cheery-pick the fix to production?

One strange thing is that on Firefox I get the NOI logo when visiting https://opendatahub.com/favicon.ico
![image](https://github.com/noi-techpark/opendatahub-website/assets/12729238/b3a37dd3-3452-461b-a1bf-986f59aaa69e)

Anyway we should use the favicon from https://third-party.opendatahub.com/opendatahub-logo/OpenDataHub-favicon.png to be reuse compliant

**Comment by ohnewein** [comment]
Hi @dulvui ,
it is not super urgent, but I would suggest to not wait too long. If you can add it to your next sprint, that would be fine for me.
Best regards,
Patrick

**Comment by sseppi** [comment]
@ohnewein I think we can close this issue since the favicon is now working.
