### ISSUE TITLE
As an Open Data Hub user I would like to find a "Open Data Hub Contributor of the Year" page on the Open Data Hub website

### ISSUE THREAD

**Issue by emilylouisesimonis** [noi-techpark/opendatahub-website#238]
We would like to create an 'Open Data Hub Contributor of the Year' page, similar to the SFS Award page on the SFSCON.it website. Please take a look at: https://www.sfscon.it/awards/ and https://www.sfscon.it/awards/sfs-award-2023/.

The description of the page follows in the comment.

**Comment by emilylouisesimonis** [comment]
### **Menu**

We would add a "**Contributor of the Year**" entry to the menu under the "Community" voice, as shown in the following screenshot:
![Contributoroftheyear](https://github.com/noi-techpark/opendatahub-website/assets/38345889/a1cbfc55-04b0-42ad-b3f1-b99e59194e6d)

### **Page content**

We would use the page format we used for https://opendatahub.com/about-us/

**Text**:

**Laudatio for the Open Data Hub Contributor of the Year 2024**
It is with great pride that we gather here today to present the first “Open Data Hub Contributor of the Year” Award. 
This award has been established to honour an individual whose contributions have significantly advanced the goals and impact of the Open Data Hub. 
This award is not simply a recognition of technical skills or innovative ideas; it is a celebration of the spirit of collaboration, the drive for excellence and the commitment to fostering a vibrant and supportive community around our shared vision.
It is this spirit that we seek to recognise and promote through this award, encouraging others to follow in the footsteps of those who exemplify these values.
This year's recipient of the Open Data Hub Contributor of the Year Award is someone who embodies the very essence of what this recognition stands for. Despite his youth, he has become an inspiration within our community, proving that intellect and dedication know no age limits when it comes to making impactful contributions.
He has been a transformative presence within the Open Data Hub. His insightful suggestions and proactive engagement have not only driven numerous improvements, but also fostered a culture of thoughtful innovation and collaboration.
In recognising him as the Open Data Hub Contributor of the Year, we celebrate not only his individual achievements, but also the immense potential of our community. He is a testament to the fact that each of us, regardless of age or background, can have a significant impact on shaping the future of open data and digital innovation.
Let his story inspire us all to excel as we continue to contribute to the development of the Open Data Hub.
And now, it is my great honour and privilege to announce that the Open Data Hub Contributor of the Year 2024 is…  Henri Egger.
Congratulations Henri! Your dedication and contributions are an inspiration to us all.

**Comment by d3liaa** [comment]
hi @emilylouisesimonis ,
i will start working on it now. I will update you as soon as possible.

**Comment by d3liaa** [comment]
hi @emilylouisesimonis 
you can find the requested addition to the website here: https://opendatahub.testingmachine.eu/community/contributor-of-the-year/

If you have notes or questions let me know:))

Have a nice day,
Delia

**Comment by sseppi** [comment]
@emilylouisesimonis @d3liaa since today we published this section in production I close this issue. If you any bug or missing feature, feel free to reopen the issue.
