### ISSUE TITLE
As a Open Data Hub website visitor I want a anchor functionality in the Video Library section, to share a specific section or video with other people

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/opendatahub-website#240]
Since the number of sections and videos of the video library became quite large, it is difficult to find and share a specific video with other people.

https://opendatahub.com/events/video-library/

I wold like that a anchor functionality is added to the single page. This functionality should allow the user to share:

- **a section**: the user that opens the shared link should see directly the shared section opened with all other section closed
- **a specific video**: the user that opens the shared link should see directly the specific video (the entire section where the video i integrated is open and all other section are closed)

**Comment by lukmay** [comment]
Hi @sseppi . I implemented the changes here: [PR](https://github.com/noi-techpark/opendatahub-website/pull/243)
I'm a bit unsure about the location of the JavaScript code.
I also add a lot of comments to it so it's clear what it does.

https://github.com/noi-techpark/opendatahub-website/tree/anchor_links_videos
Let me know if it is as you expected it to be👍

**Comment by sseppi** [comment]
Hi @lukmay ,

I collected the following feedback from Patrick:

--------------
- https://opendatahub.com/events/video-library/#open-data-hub-insights 
Does scroll to much and the videos are hidden, because the tree-view is collapsed. As user I do not understand where a video should be, I just see labels.
![Screenshot from 2024-07-26 14-21-22](https://github.com/user-attachments/assets/cf05db70-63be-4494-9f6d-f92866ed97d6)
- https://opendatahub.com/events/video-library/#stuart-implementing-a-chatbot-using-llm-and-rag---for-developers
Does scroll to much and part of the videos are hidden.
![Screenshot from 2024-07-26 14-21-09](https://github.com/user-attachments/assets/bdaf3aa4-8b50-4d11-b357-7ce669b50f61)

This makes sharing on social media channels of the single videos impossible.
-------------

**Expected behaviour**
- In case a user shares a entire video library section the section should be open per default and all other section closed and positioned in a way that the title is visible. As for example by sharing the "Open Data Hub Insight" (https://opendatahub.com/events/video-library/#open-data-hub-insights) section the view should be the following:
![Screenshot from 2024-07-26 14-26-21](https://github.com/user-attachments/assets/16402f68-f472-478e-a0e1-138064d27127)
- In case a user shares a single video, the shared video should be the first one on the top of the page with all content visible. As for example by sharing the "Stuart: Implementing a chatbot using LLM and RAG - For developers" (https://opendatahub.com/events/video-library/#stuart-implementing-a-chatbot-using-llm-and-rag---for-developers) section the view should be the following:
![Screenshot from 2024-07-26 14-29-09](https://github.com/user-attachments/assets/e230aa0f-9f8e-42b1-b4ce-92a9b04bf520)

Can you please change the code of the page to fit what mentioned above?

**Comment by lukmay** [comment]
Hi @sseppi
Thank you for sharing this feedback!
I will make the enhancements and fixes when I'm back from vacation mid-next week.
If this is more urgent and can't wait until next week, let me know and we will find a solution.

**Comment by sseppi** [comment]
@lukmay the anchor functionality seems to work fine now, I close the issue.
