### ISSUE TITLE
As an Open Data Hub website PM I would like to activate contact form functionality

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/opendatahub-website#29]
- [x] reuse the application developed for the form functionality of the Free Software Lab
- [x] integrate it in the website template developed by FlashBeing
- [x] also contact form page needs to be configured (https://opendatahub.bz.it/start/)

**Comment by bertolla** [comment]
@LucaMiotto 
Should be working fine now.
If you can do one last check I also change the receiving mail address to help@opendatahub.bz.it

**Comment by LucaMiotto** [comment]
@bertolla It works, thanks Patrick!

**Comment by bertolla** [comment]
@LucaMiotto 
I first thought that the backend was failing but it's already in the frontend:
![image](https://user-images.githubusercontent.com/3582457/123592832-0cb04900-d7ee-11eb-8a7e-1f14b3ce5ba3.png)
Can you tell 'em  to fix this and to test it before they do another pull-request?
