### ISSUE TITLE
Lukas asks to use the BW Logo of Open Data Hub and NOI

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#40]
- [x] change Open Data Hub logo to B/W version
- [x] add NOI Logo (b/w version)
- [x] change green color to dark green ( R 80 | G 116 | B 47 ) Hex #50742F

Logos can be found in the following folder:
https://noibz.sharepoint.com/:f:/s/UnitBrandCommunication/Em_9tnh1vl1AgAfmPuOoTRgB2EKrn9qzl39S0X4PTodstQ?e=plXhm3

![Screenshot from 2021-06-18 16-27-48](https://user-images.githubusercontent.com/414797/122576610-24e7d180-d052-11eb-82b3-8201aa6e2c52.png)

**Comment by LucaMiotto** [comment]
Requested modifications done, please test it @ohnewein
