### ISSUE TITLE
Users should see also NOI as Data Provider (Events, ...) and Data Consumer (today, ...) on the Open Data Hub website

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#55]
- [x] add NOI as Data Provider on https://opendatahub.bz.it/community/
- [x] add NOI as Data Consumer on https://opendatahub.bz.it/community/

**Comment by LucaMiotto** [comment]
Done. Please test it.

**Comment by ohnewein** [comment]
Works. Thanks!

I noticed that some logos, like NOI and Schwarzenstein are not really sharp. Is this due of my smartphone or have these logos been rescaled with law quality?
