### ISSUE TITLE
Spelling error: Whe instead of We

### ISSUE THREAD

**Issue by ohnewein** [noi-techpark/opendatahub-website#57]
Misspelled "whe have the data for that.“ should be "we have the data for that."

https://opendatahub.bz.it/data-access/

![Screenshot_20210804-094105](https://user-images.githubusercontent.com/414797/128141884-2c480d09-3fee-4277-87c8-24fa3c6083db.jpg)

**Comment by emilylouisesimonis** [comment]
The texts have been improved with the new release of the opendatahub.com.
