### ISSUE TITLE
Titles of Datasets are not clear

### ISSUE THREAD

**Issue by RudiThoeni** [noi-techpark/opendatahub-website#74]
https://opendatahub.bz.it/datasets/

Displaying Accommodations (1), Accommodations (2), Accommodations (3) OR Activities & Pois (1) etc...
confuses.... maybe the title should already explain what the dataset is about

**Comment by RudiThoeni** [comment]
![image](https://user-images.githubusercontent.com/30471361/134143866-8f98b956-c3c7-49b5-99a8-042672e6b57b.png)

**Comment by d3liaa** [comment]
I would suggest: 
accomodation(1) -->Accomodation(open data)
accomodation(2) -->Accomodation(partially closed data)
accomodation(3) -->Accomodation(closed data)

Activities & Pois (1)-->Activities & Pois & Gastronomy
Activities & Pois (2)-->Points of Interests
Activities & Pois (3)-->Activities
Activities & Pois (4)-->Gastronomy

Location & Commons(1)-->Locations
Location & Commons(2)-->Tourism regions
Location & Commons(3)-->District and municipalities

Traffic Station(1)-->Traffic station on A22
Traffic Station(2)-->Electronic road signs on A22

**Comment by emilylouisesimonis** [comment]
The dataset titles have been improved with the new release of the datasets page.
